### ISSUE TITLE
Blender 3.2 error

### ISSUE THREAD

**Issue by 3dcinetv** [BlenderNPR/Abnormal#22]
Hello. I'm trying to install ABNormal 1.1 in Blender 3.2 but I get the following error:
Python: Traceback (most recent call last):
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\operators_modal.py", line 241, in invoke
    self._container = ABNContainer(
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\classes.py", line 12, in __init__
    self.create_shader()
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\classes.py", line 95, in create_shader
    self.shader = gpu.types.GPUShader(vertex_shader, fragment_shader)
Exception: Shader Compile Error, see console for more details

location: <unknown location>:-1

**Comment by CodyWinch** [comment]
I cannot replicate the issue as it works for me in 3.2

Can you post a full screenshot of your system console? I think there should be more information on what the actual error is.

Alternatively in the addon user preferences in the Behavior section you can turn on the Use Alternate Mac Shading option and see if that works.

**Comment by 3dcinetv** [comment]
Here's the console error:
ERROR (gpu.shader): pyGPUShader FragShader:
      |
   51 |                 gl_FragColor = vec4(rgba.xyz * brightness, rgba.a);
      |
      | Error: C7616: global variable gl_FragColor is removed after version 420

Python: Traceback (most recent call last):
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\operators_modal.py", line 241, in invoke
    self._container = ABNContainer(
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\classes.py", line 12, in __init__
    self.create_shader()
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\classes.py", line 95, in create_shader
    self.shader = gpu.types.GPUShader(vertex_shader, fragment_shader)
Exception: Shader Compile Error, see console for more details

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\operators_modal.py", line 241, in invoke
    self._container = ABNContainer(
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\classes.py", line 12, in __init__
    self.create_shader()
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\classes.py", line 95, in create_shader
    self.shader = gpu.types.GPUShader(vertex_shader, fragment_shader)
Exception: Shader Compile Error, see console for more details

location: <unknown location>:-1

**Comment by 3dcinetv** [comment]
On version 1.1, Behavior > Use rotation gizmo and Edit Split individual loops. No other options.

**Comment by CodyWinch** [comment]
Update to the current Master version instead of the 1.1 release. That error is fixed in master

**Comment by 3dcinetv** [comment]
Ok, I installed "master" addon zip, on  Blender 3.2, 
I activate it with a suzzane money selected.
Changed the UI size of ABnormal.
Instant crash of the AbNormal UI, cursor cannot go over the 3D viewport, only appear on top of the viewport settings. The mouse is not drawn into the 3D GL viewport.

CONSOLE:
Python: Traceback (most recent call last):
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\operators_modal.py", line 67, in modal
    status = basic_ui_hover_keymap(self, context, event)
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\functions_keymaps.py", line 18, in basic_ui_hover_keymap
    self._window.click_down_move(
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\cui_classes\cui_window.py", line 220, in click_down_move
    panel.click_down_move(
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\cui_classes\cui_window.py", line 726, in click_down_move
    super().click_down_move(mouse_co, shift, self.position, arguments)
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\cui_classes\cui_containers.py", line 377, in click_down_move
    cont.click_down_move(mouse_co, shift, [
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\cui_classes\cui_containers.py", line 377, in click_down_move
    cont.click_down_move(mouse_co, shift, [
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\cui_classes\cui_containers.py", line 889, in click_down_move
    item.click_down_move(mouse_co, shift, [
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\cui_classes\cui_items.py", line 994, in click_down_move
    bpy.context.window.cursor_warp(
TypeError: Window.cursor_warp(): error with argument 1, "x" -  Function.x expected an int type, not float

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\operators_modal.py", line 67, in modal
    status = basic_ui_hover_keymap(self, context, event)
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\functions_keymaps.py", line 18, in basic_ui_hover_keymap
    self._window.click_down_move(
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\cui_classes\cui_window.py", line 220, in click_down_move
    panel.click_down_move(
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\cui_classes\cui_window.py", line 726, in click_down_move
    super().click_down_move(mouse_co, shift, self.position, arguments)
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\cui_classes\cui_containers.py", line 377, in click_down_move
    cont.click_down_move(mouse_co, shift, [
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\cui_classes\cui_containers.py", line 377, in click_down_move
    cont.click_down_move(mouse_co, shift, [
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\cui_classes\cui_containers.py", line 889, in click_down_move
    item.click_down_move(mouse_co, shift, [
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal-master\cui_classes\cui_items.py", line 994, in click_down_move
    bpy.context.window.cursor_warp(
TypeError: Window.cursor_warp(): error with argument 1, "x" -  Function.x expected an int type, not float

location: <unknown location>:-1


Something is wrong, clear out 3D Draw Handler
Something is wrong, clear out 2D Draw Handler

**Comment by 3dcinetv** [comment]
On the next Blender 3.2 restart, the ABNormal addon automatically removed itself after the Ui hard crash.
Blender does not show ABNormal addon tab on the N panel in the 3D viewport after the restart from the UI crash.

**Comment by CodyWinch** [comment]
I just pushed a fix for the cursor warp error.

**Comment by 3dcinetv** [comment]
Awesome, it works! I can resize the Ui. I also tested the split normals options, this is fantastic. Thank you!
