### ISSUE TITLE
crash on box select or use of rotation tool

### ISSUE THREAD

**Issue by DCLzexon** [BlenderNPR/Abnormal#25]
as said on the tin, I cant use some of the better features of abnormal because of it and I have no idea what is going on. Logs say to clear out 2d/3d view handler. Google gives no advice as to what that means or how to do it. On 3.2 using version 1.2. Tried a fresh download and re install. Seems to be a TypeError: mathutil.Vector(). Zero idea what I could be doing wrong. 

error is Python: Traceback (most recent call last):
  File "C:\Users\Deryian\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal\operators_modal.py", line 64, in modal
    refresh_batches(self, context)
  File "C:\Users\Deryian\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal\functions_drawing.py", line 13, in refresh_batches
    create_selection_drawing_lists(modal)
  File "C:\Users\Deryian\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Abnormal\functions_drawing.py", line 231, in create_selection_drawing_lists
    init_loc = Vector(modal._mode_cache[0][0]).xy
TypeError: mathutils.Vector()

**Comment by CodyWinch** [comment]
I just pushed a fix for this. Please redownload and give it another try to see if it is fixed for you

**Comment by DCLzexon** [comment]
hadn't expected such a quick reply. Uninstalled the last version, re-installed the update, restarted blender, and the box select worked. So to did the rotate gizmo as well! Thank you for the quick reply and fix. Im glad I can now continue to use this add on in my work flow.
