### ISSUE TITLE
Error while using lasso select

### ISSUE THREAD

**Issue by df-0** [BlenderNPR/Abnormal#3]
got the following error, blender 2.82 on windows 10

```
location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\davef\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Abnormal-master\operators_modal.py", line 63, in modal
    status = lasso_select_keymap(self,context, event)
  File "C:\Users\davef\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Abnormal-master\functions_keymaps.py", line 1071, in lasso_select_keymap
    sel_res = lasso_selection_test(self, context, event)
  File "C:\Users\davef\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Abnormal-master\functions_modal.py", line 1713, in lasso_selection_test
    in_range_inds = bounding_box_filter(self._changing_po_cache, [ view3d_utils.location_3d_to_region_2d(region, rv3d, po.co) for po in self._points_container.points])
  File "C:\Users\davef\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Abnormal-master\functions_general.py", line 194, in bounding_box_filter
    in_range_cos = [c for c, co in enumerate(cos) if min_x < co[0] < max_x and min_y < co[1] < max_y]
  File "C:\Users\davef\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Abnormal-master\functions_general.py", line 194, in <listcomp>
    in_range_cos = [c for c, co in enumerate(cos) if min_x < co[0] < max_x and min_y < co[1] < max_y]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by CodyWinch** [comment]
Fixed in newest update
