### ISSUE TITLE
Shader compile Error in Blender 4.01 - on Mac

### ISSUE THREAD

**Issue by bluepuppy** [BlenderNPR/Abnormal#32]
Python: Traceback (most recent call last):
  File "/Users/XXXXXX/Library/Application Support/Blender/4.0/scripts/addons/Abnormal-master/operators_modal.py", line 235, in invoke
    self._container = ABNContainer(
  File "/Users/XXXXXX/Library/Application Support/Blender/4.0/scripts/addons/Abnormal-master/classes.py", line 15, in __init__
    self.create_shader()
  File "/Users/XXXXXXX/Library/Application Support/Blender/4.0/scripts/addons/Abnormal-master/classes.py", line 114, in create_shader
    self.shader = gpu.types.GPUShader(vertex_shader, fragment_shader)
Exception: Shader Compile Error, see console for more details

**Comment by CodyWinch** [comment]
![image](https://github.com/bnpr/Abnormal/assets/10019228/0f4e8ea8-7179-43b5-b2a3-833f14c87f4f)

Try turning on the alternative drawing option in the addon preferences
